[/Script/Engine.GameUserSettings]
; 해상도 0은 시스템 기본값을 사용하라는 의미로 해석될 수 있습니다.
ResolutionSizeX=0
ResolutionSizeY=0
LastUserConfirmedResolutionSizeX=0
LastUserConfirmedResolutionSizeY=0
WindowPosX=-1
WindowPosY=-1
; FullscreenMode 1은 전체 화면(Fullscreen)입니다. (0: 전체화면, 1: 창모드 전체화면, 2: 창모드)
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
Version=5
; 렌더링 퀄리티 및 해상도 스케일 100% 강제
ScalabilityQuality=3
sg.ResolutionQuality=100.000000
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.GlobalIlluminationQuality=3
sg.ReflectionQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.FoliageQuality=3
sg.ShadingQuality=3
sg.MeshPaintQuality=3
